version: '3.6'
services: 
    node:
        build: .
        restart: always
        depends_on: 
            - mongo
        volumes: 
            - ./:/home/node/app
        ports: 
            - 3000:3000
    mongo:
        image: mongo:4.2
        restart: always
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 123
        ports: 
            - 27017:27017